#! /bin/bash
echo Starting Scrip
echo There were $# parameters supplied
set -e
conf_file=$1

complete_arguments=$@
echo complete_arguments $complete_arguments
shift

while [ -n "$1" ]
do
   echo "$1"
   case "$1" in
     -d) data_dir=$2
         echo Found data_dir: $data_dir
         shift;;
     -s) echo Found dbname=$2
         echo dbname: $dbname
         shift;;
     -t) echo Found threads: $2
         shift;;
     -v) echo Found verbose: $2
         shift;;
      *) echo $1 is not an option ;;
   esac
   shift
done

temp_dir="${data_dir}"_temp
echo temp_dir: temp_dir
mkdir -p "$temp_dir"

shopt -s extglob
mv "${data_dir}/"!(*schema*.sql|metadata) "${temp_dir}" 
#mv "${data_dir}/"*.sql "${temp_dir}/"
echo Moved sql data files to temp dir

myloader --defaults-file="$conf_file" $complete_arguments 
echo Loaded base database schema

mysql --defaults-file="$conf_file" -NBe "set @db='${dbname}'; source index_generator.sql;" >"${temp_dir}/add_index.sql"
echo Exported index creation query files

mysql --defaults-file="$conf_file" -NBe "set @db='${dbname}'; source drop_generator.sql;" >"${temp_dir}/drop_index.sql"
echo Exported drop index query files

mysql --defaults-file="$conf_file" -NBe "use ${dbname}; source ${temp_dir}/drop_index.sql;"
echo Executed drop queries

mv "${temp_dir}/"!(*_index.sql) "${data_dir}/"
echo Moving data sql queries back to data dir

mv "${data_dir}/"*schema*.sql "${temp_dir}/"
echo Moved schema query to temp dir

myloader --defaults-file="$conf_file" $complete_arguments
echo Loaded Data into database

mv "${temp_dir}/"add_index.sql "${data_dir}/"
mysql --defaults-file="$conf_file" -NBe "use ${dbname}; source ${data_dir}/add_index.sql;"
echo Added Indexes

mv "${temp_dir}/"*schema*.sql "${data_dir}/"
mv "${data_dir}/"*_index.sql "${temp_dir}/"
echo Cleaning up

shopt -u extglob
echo Done!!

